import './globals/globals.css'

import { LATO_REGULAR } from './globals/font'

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" className={LATO_REGULAR.className}>
			<head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body>
				{children}
			</body>
		</html>
	)
}
