import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { ThemeHtml } from "@/components/theme";

const lato = Lato({
  weight: ['300', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeHtml>
      <body
        className={`${lato.className} antialiased bg-slate-100 dark:bg-slate-900 text-slate-900 dark:text-slate-100`}
      >
        {children}
      </body>
    </ThemeHtml>
  );
}
